// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2li9gsTiSkkdGALjDzdlbVe1y-uHvgjY',
    appId: '1:619377035488:web:1b1af70bb4fb827820e885',
    messagingSenderId: '619377035488',
    projectId: 'project-8045',
    authDomain: 'project-8045.firebaseapp.com',
    storageBucket: 'project-8045.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAza-UpgA9iQ8NEFeKPGGcbuvX8kfLgHdw',
    appId: '1:619377035488:android:292563a488d6409520e885',
    messagingSenderId: '619377035488',
    projectId: 'project-8045',
    storageBucket: 'project-8045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlJWmyizRHfzNDXbyOn2BYGyyNcknHyY4',
    appId: '1:619377035488:ios:1930f2e6d2888bca20e885',
    messagingSenderId: '619377035488',
    projectId: 'project-8045',
    storageBucket: 'project-8045.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlJWmyizRHfzNDXbyOn2BYGyyNcknHyY4',
    appId: '1:619377035488:ios:1930f2e6d2888bca20e885',
    messagingSenderId: '619377035488',
    projectId: 'project-8045',
    storageBucket: 'project-8045.appspot.com',
    iosBundleId: 'com.example.project2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQk2zWfXI8ejBRP2o_-fMnep-0M92B5CE',
    appId: '1:619377035488:web:ad1c4388e8be23d720e885',
    messagingSenderId: '619377035488',
    projectId: 'project-8045',
    authDomain: 'project-8045.firebaseapp.com',
    storageBucket: 'project-8045.appspot.com',
  );
}
